version: "3.5"
services:
  db:
    image: postgres:15
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: unless-stopped

  web:
    build: .
    command: ./scripts/docker-entrypoint.sh
    init: true
    volumes:
      - .:/app
      - node_modules:/app/node_modules # ensures we retain node_modules from docker build
      - bundle:/usr/local/bundle
      - /var/run/docker.sock:/var/run/docker.sock
      - ssh:/root/.ssh
      - bash_history:/root/.bash_history
    ports:
      - "3030:3000"
    depends_on:
      - db
    environment:
      - RAILS_DEV_DB_PASS=password
      - WEBPACKER_DEV_SERVER_HOST=web
    stdin_open: true
    tty: true # Allow interactive byebug sessions
    restart: unless-stopped

volumes:
  bundle: null
  pg-data: null
  node_modules: null
  ssh: null
  bash_history: null
